/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dissys.ca1dis;

import io.grpc.stub.StreamObserver;
import generated.grpc.sustainableActivityService.ActivityRequest;
import generated.grpc.sustainableActivityService.ActivityReply;
import generated.grpc.sustainableActivityService.ActivityType;

import userAndServer.RCPgameClient;

/**
 *
 * @author brad1109
 */
public class MainServerGui extends javax.swing.JFrame {

    // client side
    private final RCPgameClient client;

    // the collection to ready for multiple requests
    private StreamObserver<ActivityRequest> activityReqObs = null;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainServerGui.class.getName());

    /**
     * Creates new form MainServerGui
     */
    public MainServerGui(RCPgameClient client) {
        this.client = client;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productIdLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        ResultLabel = new javax.swing.JLabel();
        productIdLabel = new javax.swing.JLabel();
        productIdTextField = new javax.swing.JTextField();
        activityTypeLabel = new javax.swing.JLabel();
        walkButton = new javax.swing.JToggleButton();
        metroButton = new javax.swing.JToggleButton();
        busButton = new javax.swing.JToggleButton();
        doneButton = new javax.swing.JToggleButton();
        petRequestButton = new javax.swing.JButton();
        petLabel = new javax.swing.JLabel();
        productIdButton1 = new javax.swing.JButton();

        productIdLabel1.setText("Product ID:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Responsible Consumption & Production Game");

        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        jScrollPane1.setViewportView(resultTextArea);

        ResultLabel.setText("Result : ");

        productIdLabel.setText("Product ID :");

        activityTypeLabel.setText("Activity Type :");

        walkButton.setText("WALK");
        walkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walkButtonActionPerformed(evt);
            }
        });

        metroButton.setText("METRO");
        metroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metroButtonActionPerformed(evt);
            }
        });

        busButton.setText("BUS");
        busButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busButtonActionPerformed(evt);
            }
        });

        doneButton.setText("DONE");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        petRequestButton.setText("Request");
        petRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petRequestButtonActionPerformed(evt);
            }
        });

        petLabel.setText("Pet Status : ");

        productIdButton1.setText("Go");
        productIdButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIdButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(250, 250, 250))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResultLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productIdLabel)
                            .addComponent(activityTypeLabel)
                            .addComponent(petLabel))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(walkButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(metroButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(busButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doneButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(productIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(productIdButton1))
                            .addComponent(petRequestButton))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productIdLabel)
                    .addComponent(productIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productIdButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activityTypeLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(walkButton)
                        .addComponent(metroButton)
                        .addComponent(busButton)
                        .addComponent(doneButton)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petRequestButton)
                    .addComponent(petLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(ResultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void walkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walkButtonActionPerformed
        // TODO add your handling code here:
        ensureActivityStream();
        activityReqObs.onNext(ActivityRequest.newBuilder().setActivityType(ActivityType.WALK).build());
        resultTextArea.append("Sent: WALK\n");
    }//GEN-LAST:event_walkButtonActionPerformed

    private void metroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metroButtonActionPerformed
        // TODO add your handling code here:
        ensureActivityStream();
        activityReqObs.onNext(ActivityRequest.newBuilder().setActivityType(ActivityType.METRO).build());
        resultTextArea.append("Sent: METRO\n");
    }//GEN-LAST:event_metroButtonActionPerformed

    private void busButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busButtonActionPerformed
        // TODO add your handling code here:
        ensureActivityStream();
        activityReqObs.onNext(ActivityRequest.newBuilder().setActivityType(ActivityType.BUS).build());
        resultTextArea.append("Sent: BUS\n");
    }//GEN-LAST:event_busButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
        if (activityReqObs == null) {
            resultTextArea.append("No activity to finish.\n");
            return;
        }
        resultTextArea.append("DONE sent.\n");
        activityReqObs.onCompleted();
        activityReqObs = null;
    }//GEN-LAST:event_doneButtonActionPerformed

    private void productIdButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIdButton1ActionPerformed
        // TODO add your handling code here:
        // input produc ID; return product detail
        String productId = productIdTextField.getText().trim();
        // if it is empty
        if (productId.isEmpty()) {
            resultTextArea.setText("Please, scan product ID. (e.g., A01)");
        }

        // set button
        productIdButton1.setEnabled(false);
        resultTextArea.setText("");
        resultTextArea.setText(productId + " is loadding...\n");
        // set thread
        new Thread(() -> {
            client.productTrack(
                    productId,
                    reply -> javax.swing.SwingUtilities.invokeLater(() -> {
                        resultTextArea.append(
                                "ProductId: " + reply.getProductId()
                                + "\nManufacturer: " + reply.getManufacturer()
                                + "\nDescription: " + reply.getDescription()
                                + "\nCarbon: " + reply.getCarbon()
                                + "\nImpactPoint: " + reply.getImpactPoint()
                                + "\n\n"
                        );
                    }),
                    err -> javax.swing.SwingUtilities.invokeLater(() -> {
                        resultTextArea.append("Error: " + err.getMessage() + "\n");
                        productIdButton1.setEnabled(true);
                    }),
                    () -> javax.swing.SwingUtilities.invokeLater(() -> {
                        resultTextArea.append("Completed\n");
                        productIdButton1.setEnabled(true);
                    })
            );
        }).start();


    }//GEN-LAST:event_productIdButton1ActionPerformed

    private void petRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petRequestButtonActionPerformed

        resultTextArea.setText("");
        petRequestButton.setEnabled(false);

        new Thread(() -> {
            client.getVirtualStatus(
                    reply -> javax.swing.SwingUtilities.invokeLater(() -> {
                        resultTextArea.setText(
                                "Level=" + reply.getLevel()
                                + ", credit=" + reply.getPersonalCredit().getTotalCredit() + "\n"
                        );
                    }),
                    err -> javax.swing.SwingUtilities.invokeLater(() -> {
                        resultTextArea.setText("Error: " + err.getMessage() + "\n");
                        petRequestButton.setEnabled(true);
                    }),
                    () -> javax.swing.SwingUtilities.invokeLater(() -> {
                        resultTextArea.append("Completed\n");
                        petRequestButton.setEnabled(true);
                    })
            );
        }).start();
    }//GEN-LAST:event_petRequestButtonActionPerformed

    // methods
    private void ensureActivityStream() {
        if (activityReqObs != null) {
            return;
        }

        resultTextArea.setText("");
        resultTextArea.append("Activity tracking started...\n");

        activityReqObs = client.activityTrack(
                // server the last return ActivityReply（summary）
                reply -> javax.swing.SwingUtilities.invokeLater(() -> {
                    resultTextArea.append("\n=== Summary ===\n");
                    resultTextArea.append("Date: " + reply.getDay() + "\n");
                    resultTextArea.append("Total credit: " + reply.getPersonalCredit().getTotalCredit() + "\n");
                    resultTextArea.append("Total carbon: " + reply.getSummary().getCarbon() + "\n");
                }),
                err -> javax.swing.SwingUtilities.invokeLater(() -> {
                    resultTextArea.append("Error: " + err.getMessage() + "\n");
                    activityReqObs = null;
                }),
                () -> javax.swing.SwingUtilities.invokeLater(() -> {
                    resultTextArea.append("Activity stream completed.\n");
                })
        );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JLabel activityTypeLabel;
    private javax.swing.JToggleButton busButton;
    private javax.swing.JToggleButton doneButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton metroButton;
    private javax.swing.JLabel petLabel;
    private javax.swing.JButton petRequestButton;
    private javax.swing.JButton productIdButton1;
    private javax.swing.JLabel productIdLabel;
    private javax.swing.JLabel productIdLabel1;
    private javax.swing.JTextField productIdTextField;
    private javax.swing.JTextArea resultTextArea;
    private javax.swing.JToggleButton walkButton;
    // End of variables declaration//GEN-END:variables
}
