/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package dissys.ca1dis;
// tools
import java.util.logging.Logger;
import io.grpc.Server;
import io.grpc.ServerBuilder;
import java.io.IOException;
import java.time.LocalTime;
// generated by gRPC
import generated.grpc.productTrackService.ProductReply;
import generated.grpc.productTrackService.ProductRequest;
import generated.grpc.productTrackService.ProductTrackGrpc.ProductTrackImplBase;
import io.grpc.stub.StreamObserver;
// DB
import data.product.ProductMap;
import data.product.Product;

// jmdns
import jmdns.ServiceRegistration;
import java.net.InetAddress;
import javax.jmdns.JmDNS;
import javax.jmdns.ServiceInfo;

/**
 *
 * @author brad1109
 */
public class ProducttrackServer extends ProductTrackImplBase {

    // Logger class to track info 
    private static Logger logger = Logger.getLogger(ProducttrackServer.class.getName());

        // single register for testing
    public static void main(String[] args){
        Logger logger = Logger.getLogger(LoginServer.class.getName());
        // intance class
        ProducttrackServer producttrackServer = new ProducttrackServer();
        int port = 50051;
        try{
            // Create Server 
            Server server = ServerBuilder.forPort(port).addService(producttrackServer).build().start();
            
            logger.info("Server started, listening on " + port);
            server.awaitTermination();
        }catch(IOException e){
            e.printStackTrace();
        }catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    
    }

    /**
     * Bidi get the product info rpc rpc PurchaseTrack(stream ProductRequest)
     * returns (stream ProductReply);
     *
     * @param responseObserver - response to the client is return via this
     * object
     * @return     double carbon = 1; string manufacturer =2; string description =3; int32 impactPoint =4; string productId = 5;
     */
    @Override
    public StreamObserver<ProductRequest> purchaseTrack(StreamObserver<ProductReply> responseObserver) {

        return new StreamObserver<ProductRequest>() {
            // intantail class as a helper object as a mock DB
            ProductMap productMap = new ProductMap();

            @Override
            public void onNext(ProductRequest v) {
                // tracking info
                System.out.println(LocalTime.now().toString() + ": received message: " + v.getProductId());
                // the server wil use the Prodeuct ID to look up the info
                // gets all the info recorded for the product ID and returns the first one on the list
                Product p = productMap.getInfoById(v.getProductId());
                if (p == null) {
                    ProductReply reply = ProductReply.newBuilder().setProductId("Not Data: " + v.getProductId()).build();
                    responseObserver.onNext(reply);
                    return;
                };
                // set reply variables
                double carbon = p.getCarbon();
                String manufacturer = p.getManufactuer();
                String description = p.getDecription();
                int impactPoint = productMap.getImapcById(v.getProductId());
                String productId = p.getProductId();
                // build reply; wrap it all.
                ProductReply reply = ProductReply.newBuilder()
                        .setProductId(productId)
                        .setManufacturer(manufacturer)
                        .setDescription(description)
                        .setCarbon(carbon)
                        .setImpactPoint(impactPoint)
                        .build();
                responseObserver.onNext(reply);

            }

            @Override
            public void onError(Throwable thrwbl) {
                // TODO Auto-generated method stub
                logger.warning(LocalTime.now() + ": purchaseTrack error: " + thrwbl.getMessage());
            }

            @Override
            public void onCompleted() {
                System.out.printf(LocalTime.now().toString() + ": Message stream complete \n");
                // the server signals that it is finished
                responseObserver.onCompleted();
            }

        };
    }

}
