/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package dissys.ca1dis;

// tools
import java.util.logging.Logger;
import java.time.LocalTime;
import java.util.ArrayList;
import io.grpc.stub.StreamObserver;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

// generated by gRPC
import generated.grpc.sustainableActivityService.ActivityTrackGrpc.ActivityTrackImplBase;
import generated.grpc.sustainableActivityService.ActivityReply;
import generated.grpc.sustainableActivityService.ActivityRequest;

// message
import generated.grpc.sustainableActivityService.ActivitySummary;
import generated.grpc.sustainableActivityService.PersonalCredit;
import generated.grpc.sustainableActivityService.ActivityType;

/**
 *
 * @author brad1109
 */
public class SustainableTrackServer extends ActivityTrackImplBase {

    // Logger class to track info 
    private static Logger logger = Logger.getLogger(SustainableTrackServer.class.getName());


    /**
     * Client Stream get the activity info rpc SustainableTrack(stream
     * ActivityRequest) returns (ActivityReply);
     *
     * @param responseObserver - response to the client is return via this
     * object
     * @return string day = 1; // DD-MM-YYYY; ActivitySummary summary = 2;
     * PersonalCredit personalCredit = 3;
     */
    @Override
    public StreamObserver<ActivityRequest> trackActivity(StreamObserver<ActivityReply> responseObserver) {
        // Request
        return new StreamObserver<ActivityRequest>() {
            // the observer will collect each number that arrives from the client into this ArrayList
            // note that this list is a member variable of the returned object
            ArrayList<Double> listCarbon = new ArrayList();
            ArrayList<Integer> listCredit = new ArrayList();

            @Override
            public void onNext(ActivityRequest v) {
                System.out.println(LocalTime.now().toString() + ": received a NumberMessage: " + v.getActivityType());
                ActivityType type = v.getActivityType();
                int credit = 0;
                double carbon = 0.0;
                switch (type) {
                    case WALK:
                        credit = 2;
                        carbon = -0.5;
                        break;
                    case METRO:
                        credit = 1;
                        carbon = 0.2;
                        break;
                    case BUS:
                        credit = 0;
                        carbon = 0.4;
                        break;
                    default:
                        credit = 0;
                        carbon = 0.0;

                }
                listCarbon.add(carbon);
                listCredit.add(credit);
            }

            @Override
            public void onError(Throwable thrwbl) {
                // TODO Auto-generated method stub
                logger.warning(LocalTime.now() + ": SustainableTrackServer error: " + thrwbl.getMessage());
            }

            @Override
            public void onCompleted() {

                System.out.printf(LocalTime.now().toString() + ": NumberMessage stream complete \n");
                // calculate
                // Sum of Credit
                int sumCredit = 0;
                for (int i = 0; i < listCredit.size(); i++) {
                    sumCredit = sumCredit + listCredit.get(i);
                }
                // Sum of Carbon
                double sumCarbon = 0.0;
                for (int i = 0; i < listCarbon.size(); i++) {
                    sumCarbon = sumCarbon + listCarbon.get(i);
                }
                // build PersonalCredit message
                PersonalCredit pc = PersonalCredit.newBuilder().setTotalCredit(sumCredit).build();
                // build ActivitySummary message
                ActivitySummary as = ActivitySummary.newBuilder().setCarbon(sumCarbon).build();
                // set reply
                String day = LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy"));
                ActivityReply reply = ActivityReply.newBuilder().setDay(day).setPersonalCredit(pc).setSummary(as).build();

                // one reply
                responseObserver.onNext(reply);

                // the server signals that it is finished
                responseObserver.onCompleted();
            }

        };
    }

}
