/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package dissys.ca1dis;

// tools
import java.util.logging.Logger;
import java.time.LocalTime;
import io.grpc.stub.StreamObserver;

// generated by gRPC
import generated.grpc.virtualPetService.VirtualPetGrpc.VirtualPetImplBase;
import generated.grpc.virtualPetService.VirtualPetReply;
import generated.grpc.virtualPetService.VirtualPetRequest;

import generated.grpc.sustainableActivityService.PersonalCredit;



/**
 *
 * @author brad1109
 */
public class VirtualPetServer extends VirtualPetImplBase {

    // Logger class to track info 
    private static Logger logger = Logger.getLogger(VirtualPetServer.class.getName());

    /**
     * SERVER STREAMING Pet status
     *
     * @param responseObserver - response to the client is return via this
     * object
     * @return: personal credit, level
     */
    public void getPetStatus(VirtualPetRequest request, StreamObserver<VirtualPetReply> responseObserver) {
        System.out.println(LocalTime.now().toString() + ": received a message: Request pet status.");
        // Validate request, but in this case is unescessary 
        // Personal Credit and level
        PersonalCredit p = PersonalCredit.newBuilder().setTotalCredit(5).build();
        // set reply
        VirtualPetReply reply = VirtualPetReply.newBuilder()
                .setPersonalCredit(p)
                .setLevel(7)
                .build();
        responseObserver.onNext(reply);
        // close
        responseObserver.onCompleted();

    }

}
