/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package dissys.ca1dis;

// tools
import java.util.logging.Logger;
import io.grpc.Server;
import io.grpc.ServerBuilder;
import java.io.IOException;
import java.time.LocalTime;
import io.grpc.stub.StreamObserver;

// generated by gRPC
import generated.grpc.virtualPetService.VirtualPetGrpc.VirtualPetImplBase;
import generated.grpc.virtualPetService.VirtualPetReply;
import generated.grpc.virtualPetService.VirtualPetRequest;

import generated.grpc.sustainableActivityService.PersonalCredit;

// jmdns
import jmdns.ServiceRegistration;
import java.net.InetAddress;
import javax.jmdns.JmDNS;
import javax.jmdns.ServiceInfo;

/**
 *
 * @author brad1109
 */
public class VirtualPetServer extends VirtualPetImplBase {

    // Logger class to track info 
    private static Logger logger = Logger.getLogger(VirtualPetServer.class.getName());

    public static void main(String[] args) throws Exception {
        // Create one or more Server instance
        VirtualPetServer virtualPetServer = new VirtualPetServer();
        // Define port number
        int port = 50051;
        // Build Server with port number and register server instance
        try{
            Server server = ServerBuilder.forPort(port).addService(virtualPetServer).build().start();
            logger.info("Server started, listening on " + port);
            // Keep server running 
            server.awaitTermination();
            // Handle Exceptions
        }catch(IOException e){
            // for start()
            e.printStackTrace();
        }catch(InterruptedException e){
            // for awaitTermination()
            e.printStackTrace();
        }
        
    }

    /**
     * SERVER STREAMING Pet status
     *
     * @param responseObserver - response to the client is return via this
     * object
     * @return: personal credit, level
     */
    public void getPetStatus(VirtualPetRequest request, StreamObserver<VirtualPetReply> responseObserver) {
        System.out.println(LocalTime.now().toString() + ": received a message: Request pet status.");
        // Personal Credit and level
        PersonalCredit p = PersonalCredit.newBuilder().setTotalCredit(5).build();
        // set reply
        VirtualPetReply reply = VirtualPetReply.newBuilder()
                .setPersonalCredit(p)
                .setLevel(7)
                .build();
        responseObserver.onNext(reply);
        // close
        responseObserver.onCompleted();

    }

}
